linters:
  enable-all: true
  disable:
    - execinquery
    - exhaustruct
    - exhaustivestruct
    - golint
    - forbidigo
    - maligned
    - interfacer
    - paralleltest
    - scopelint
    - wrapcheck
